# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"MSGMM": "MSGMM.ipynb"}

modules = ["msgmm.py"]

doc_url = "https://Dzeiberg.github.io/latentPosteriorEstimation/"

git_url = "https://github.com/Dzeiberg/latentPosteriorEstimation/tree/master/"

def custom_doc_links(name): return None
